### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by Bhumikarai** [drishya4/Herald-CMS-System#11]
Drishya, The event page lacks the high quality image. The content would look more informative and interesting with high quality image so fix the issue.

**Comment by pramodkarki12** [comment]
If you include high quality image, there would be the problem of slow reloading of pages. I think it does not matter if you have a low quality image, but we should think on providing the perfect user experience product.

**Comment by drishya4** [comment]
Okay, I will use the perfect image according to the design of our web page and try to fix that issue.

**Comment by drishya4** [comment]
I have fixed that issue. Please check the event page.
